version: '3'
services: 
  postgres:
      image: 'postgres:12.2'
  redis:
      image: 'redis:6.0-rc2'
  server:
    build:
      dockerfile: dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    enviroment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgress
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    client:
      build:
        dockerfile: Dockerfile.dev
        context: ./client
      volumes:
        - /app/node_modules
        - ./client:/app
    worker:
      build:
        dockerfile: Dockerfile.dev
        context: ./worker
      volumes:
        - /app/node_modules
        - ./worker:/app
